:- initialization(main).

main:-
  write(' ===== ex5_2 ===== '), nl,
  consult('ex5_2.pl'),
  increment(4,X),
  write(X), nl,
  sum(4,6,Y),
  write(Y), nl,
  addone([1,2,7,2], Z),
  write(Z), nl,
  write(' ===== max & min ===== '), nl,
  consult('max_min.pl'),
  max([10, 3, 6, 4, 8, 3, 2], M),
  max([3, 6, 4, 8, 3, 2], N),
  max([-3, -6, -4, -8, -3, -2], O),
  write(M), nl,
  write(N), nl,
  write(O), nl,
  min([1, 3, 6, 4, 8, 3, 2], M2),
  min([3, 6, 4, 8, 3, 2], N2),
  min([-3, -6, -4, -8, -3, -2], O2),
  write(M2), nl,
  write(N2), nl,
  write(O2), nl,
  write(' ===== vectors ===== '), nl,
  consult('vectors.pl'),
  scalarMult(3, [2, 7, 4], Result),
  write(Result), nl,
  dotProduct([2, 5, 6], [3, 4, 1], Product),
  dotProduct([2, 5, 6], [3, 4, 1, 5], Invalid1),
  dotProduct([2, 5, 6, 8], [3, 4, 1], Invalid2),
  write(Product), nl,
  write(Invalid1), nl,
  write(Invalid2), nl,
  halt.
